#!/usr/bin/env python3
import os
import sys

# Hint URL is passed as first argument
url = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("QUTE_URL")
if not url:
    sys.exit(1)

fifo = os.environ.get("QUTE_FIFO")
if not fifo:
    sys.exit(1)

with open(fifo, "w") as f:
    # Open URL in a new window
    f.write(f"open -w {url}\n")
    # Hide tabs and status bar
    f.write("config-cycle tabs.show always never\n")
    f.write("config-cycle statusbar.show always never\n")
