return {
  -- "nvim-treesitter/nvim-treesitter",
  -- branch = "main",
  -- version = false,
  -- build = function()
  --   local TS = require("nvim-treesitter")
  --   if not TS.get_installed then
  --     LazyVim.error("Restart Neovim and run :TSUpdate")
  --     return
  --   end
  --   package.loaded["lazyvim.util.treesitter"] = nil
  --   LazyVim.treesitter.build(function()
  --     TS.update(nil, { summary = true })
  --   end)
  -- end,
  -- event = { "LazyFile", "VeryLazy" },
  -- cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
  -- opts_extend = { "ensure_installed" },
  --
  -- opts = {
  --   highlight = { enable = true },
  --   indent = { enable = true },
  --   folds = { enable = true },
  --   ensure_installed = {
  --     "bash",
  --     "c",
  --     -- "diff",
  --     "html",
  --     "javascript",
  --     "jsdoc",
  --     "json",
  --     -- "jsonc",
  --     "lua",
  --     "luadoc",
  --     "markdown",
  --     "markdown_inline",
  --     -- "printf",
  --     "python",
  --     "query",
  --     "regex",
  --     "toml",
  --     "tsx",
  --     "typescript",
  --     "vim",
  --     "vimdoc",
  --     "xml",
  --     "yaml",
  --   },
  -- },
  --
  -- config = function(_, opts)
  --   local TS = require("nvim-treesitter")
  --
  --   -- Protect against outdated installs
  --   if not TS.get_installed then
  --     return LazyVim.error("Run :Lazy sync and :TSUpdate")
  --   end
  --
  --   TS.setup(opts)
  --   LazyVim.treesitter.get_installed(true)
  --
  --   local install = vim.tbl_filter(function(lang)
  --     return not LazyVim.treesitter.have(lang)
  --   end, opts.ensure_installed or {})
  --
  --   if #install > 0 then
  --     LazyVim.treesitter.build(function()
  --       TS.install(install, { summary = true }):await(function()
  --         LazyVim.treesitter.get_installed(true)
  --       end)
  --     end)
  --   end
  --
  --   vim.api.nvim_create_autocmd("FileType", {
  --     group = vim.api.nvim_create_augroup("lazyvim_treesitter", { clear = true }),
  --     callback = function(ev)
  --       local ft, lang = ev.match, vim.treesitter.language.get_lang(ev.match)
  --       if not LazyVim.treesitter.have(ft) then
  --         return
  --       end
  --
  --       local function enabled(feat, query)
  --         local f = opts[feat] or {}
  --         return f.enable ~= false
  --           and not (type(f.disable) == "table" and vim.tbl_contains(f.disable, lang))
  --           and LazyVim.treesitter.have(ft, query)
  --       end
  --
  --       if enabled("highlight", "highlights") then
  --         pcall(vim.treesitter.start, ev.buf)
  --       end
  --
  --       if enabled("indent", "indents") then
  --         LazyVim.set_default("indentexpr", "v:lua.LazyVim.treesitter.indentexpr()")
  --       end
  --
  --       if enabled("folds", "folds") then
  --         if LazyVim.set_default("foldmethod", "expr") then
  --           LazyVim.set_default("foldexpr", "v:lua.LazyVim.treesitter.foldexpr()")
  --         end
  --       end
  --     end,
  --   })
  -- end,
}
